// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Clickbtns from "./Clickbtns.bs.js";
import * as Showcount from "./Showcount.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function GroupCount(props) {
  var items = Belt_Array.range(0, 4);
  var elements = Belt_Array.map(items, (function (i) {
          return JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(Showcount.make, {
                              prop: String(i + 1 | 0)
                            }, String(i)),
                        JsxRuntime.jsx(Clickbtns.make, {
                              prop: String(i)
                            }, String(i + 20 | 0))
                      ]
                    });
        }));
  return JsxRuntime.jsx("div", {
              children: elements
            });
}

var make = GroupCount;

export {
  make ,
}
/* Clickbtns Not a pure module */
