// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ValueStore from "./ValueStore.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Showcount(props) {
  var ctx = React.useContext(ValueStore.AppContext.context);
  console.log(ctx.state.counts);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "Group " + props.prop
                    }),
                JsxRuntime.jsx("div", {
                      children: "Count:"
                    })
              ],
              style: {
                marginTop: "80px"
              }
            });
}

var make = Showcount;

export {
  make ,
}
/* react Not a pure module */
