// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Timer(props) {
  var match = React.useState(function (param) {
        return 7;
      });
  var setCount = match[1];
  React.useEffect((function (param) {
          var intervalId = setInterval((function (param) {
                  Curry._1(setCount, (function (prevCount) {
                          return prevCount + 1 | 0;
                        }));
                }), 1000);
          return (function (param) {
                    clearInterval(intervalId);
                  });
        }), []);
  return JsxRuntime.jsx("div", {
              children: "Count: " + String(match[0])
            });
}

var make = Timer;

export {
  make ,
}
/* react Not a pure module */
